spring.application.name=Phantom

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s

spring.datasource.url=jdbc:postgresql://localhost:5432/phantom
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=OFF

logging.file.name=${LOGS_ROOT:phantom-logs}/phantom.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=0
logging.logback.rollingpolicy.total-size-cap=0

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

owner.key=${OWNER_KEY}

ton.api.key=${TON_API_KEY}
ton.testnet=false

spring.web.resources.static-locations=file:${FRONTEND_PATH}

disk.root=${DISK_ROOT:phantom-disk-storage}

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=11GB
spring.servlet.multipart.location=${SPRING_MULTIPART_CACHE_ROOT:phantom-multipart-cache}
