spring.application.name=Phantom

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s
server.port=${SERVER_PORT:8080}

server.forward-headers-strategy=FRAMEWORK

spring.datasource.url=jdbc:postgresql://localhost:5432/phantom
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=OFF

logging.file.name=${LOGS_ROOT:phantom-logs}/phantom.log
logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=0
logging.logback.rollingpolicy.total-size-cap=0

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.web.resources.static-locations=file:${FRONTEND_PATH}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

owner.key=${OWNER_KEY}

ton.api.key=${TON_API_KEY}
ton.testnet=${TON_TESTNET:false}
ton.withdrawal-min-amount=${TON_WITHDRAWAL_MIN_AMOUNT:1}
ton.withdrawal-user-edge=${TON_WITHDRAWAL_USER_EDGE:0.99}
ton.min-sweep-amount=${TON_MIN_SWEEP_AMOUNT:0.01}
ton.validation-duration-s=${TON_VALIDATION_DURATION_S:28800}

lottery.ticket-cost=${LOTTERY_TICKET_COST:1}
lottery.timestamp-end=${LOTTERY_TIMESTAMP_END:86400}
lottery.timestamp-block=${LOTTERY_TIMESTAMP_BLOCK:86100}
lottery.timestamp-notification-ending=${LOTTERY_TIMESTAMP_NOTIFICATION_ENDING:85800}

disk.root=${DISK_ROOT:phantom-disk-storage}
disk.usage.base.size-mb=${DISK_USAGE_BASE_SIZE_MB:10240}
disk.usage.base.files=${DISK_USAGE_BASE_FILES:10000}
disk.usage.plus.size-mb=${DISK_USAGE_PLUS_SIZE_MB:51200}
disk.usage.plus.files=${DISK_USAGE_PLUS_FILES:50000}

spring.servlet.multipart.max-file-size=50GB
spring.servlet.multipart.max-request-size=50GB
spring.servlet.multipart.location=${SPRING_MULTIPART_CACHE_ROOT:phantom-multipart-cache}

notifications.max-history=${NOTIFICATIONS_MAX_HISTORY:10000}
notifications.max-duration-d=${NOTIFICATIONS_MAX_DURATION_D:7}

chats.max-members=${CHATS_MAX_MEMBERS:100}

rate.pagination.tokens=${RATE_PAGINATION_TOKENS:4000}
rate.pagination.seconds=${RATE_PAGINATION_SECONDS:60}

rate.crypto.tokens=${RATE_CRYPTO_TOKENS:30}
rate.crypto.seconds=${RATE_CRYPTO_SECONDS:60}

rate.lottery.tokens=${RATE_LOTTERY_TOKENS:20}
rate.lottery.seconds=${RATE_LOTTERY_SECONDS:60}

rate.send-message.tokens=${RATE_SEND_MESSAGE_TOKENS:1000}
rate.send-message.seconds=${RATE_SEND_MESSAGE_SECONDS:3600}

rate.create-chat.tokens=${RATE_CREATE_CHAT_TOKENS:50}
rate.create-chat.seconds=${RATE_CREATE_CHAT_SECONDS:28800}

rate.invite-to-chat.tokens=${RATE_INVITE_TO_CHAT_TOKENS:100}
rate.invite-to-chat.seconds=${RATE_INVITE_TO_CHAT_SECONDS:28800}

rate.send-present.tokens=${RATE_SEND_PRESENT_TOKENS:1000}
rate.send-present.seconds=${RATE_SEND_PRESENT_SECONDS:3600}

rate.download.null.tokens=${RATE_DOWNLOAD_NULL_TOKENS:5368709120}
rate.download.null.seconds=${RATE_DOWNLOAD_NULL_SECONDS:28800}

rate.upload.disk-base.tokens=${RATE_UPLOAD_DISK_BASE_TOKENS:21474836480}
rate.upload.disk-base.seconds=${RATE_UPLOAD_DISK_BASE_SECONDS:28800}

rate.download.disk-base.tokens=${RATE_DOWNLOAD_DISK_BASE_TOKENS:21474836480}
rate.download.disk-base.seconds=${RATE_DOWNLOAD_DISK_BASE_SECONDS:28800}

rate.image-compress.disk-base.tokens=${RATE_IMAGE_COMPRESS_DISK_BASE_TOKENS:49000000000}
rate.image-compress.disk-base.seconds=${RATE_IMAGE_COMPRESS_DISK_BASE_SECONDS:28800}

rate.upload.disk-plus.tokens=${RATE_UPLOAD_DISK_PLUS_TOKENS:107374182400}
rate.upload.disk-plus.seconds=${RATE_UPLOAD_DISK_PLUS_SECONDS:28800}

rate.download.disk-plus.tokens=${RATE_DOWNLOAD_DISK_PLUS_TOKENS:107374182400}
rate.download.disk-plus.seconds=${RATE_DOWNLOAD_DISK_PLUS_SECONDS:28800}

rate.image-compress.disk-plus.tokens=${RATE_IMAGE_COMPRESS_DISK_PLUS_TOKENS:490000000000}
rate.image-compress.disk-plus.seconds=${RATE_IMAGE_COMPRESS_DISK_PLUS_SECONDS:28800}
