spring.application.name=Phantom

spring.datasource.url=jdbc:postgresql://localhost:5432/phantom
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

owner.key=${OWNER_KEY}

ton.api.base-url=https://toncenter.com
ton.api.key=${TON_API_KEY}
ton.testnet=false
