package com.example.phantom.notification;

public enum NotificationType {
    PRESENT_RECEIVED,

    BANNED,
    UNBANNED,
    YOUR_MESSAGE_DELETED,
    MESSAGE_RECEIVED,
    MESSAGE_DELETED,
    NEW_CHAT,

    ROLE_CLAIMED,

    WELCOME,

    LEVEL_UP,

    BROADCAST,

    LOTTERY_IS_ENDING,
    LOTTERY_ENDED,
    YOU_WON_LOTTERY,

    MASTER_WALLET_SET,
    SWEEP_SCHEDULE_SET,
    NEW_SWEEP,
    NEW_WITHDRAWAL,
    WITHDRAWAL_FAILED
}
