package com.example.phantom.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
public enum ErrorCode {
    NOT_AUTHENTICATED(UNAUTHORIZED),
    INVALID_PASSWORD(FORBIDDEN),
    WEAK_PASSWORD(BAD_REQUEST),
    INVALID_RECOVERY_KEY(FORBIDDEN),
    BAD_RECOVERY_KEY(BAD_REQUEST),
    USERNAME_TAKEN(CONFLICT),
    USER_NOT_FOUND(NOT_FOUND),
    EMPTY_REQUEST(BAD_REQUEST),

    OWNER_KEY_INVALID(FORBIDDEN),
    OWNER_KEY_MALFORMED(BAD_REQUEST),
    OWNER_KEY_REQUIRED(FORBIDDEN),
    ROLE_REQUIRED(BAD_REQUEST),
    NOT_OWNER(FORBIDDEN),
    CANT_CHANGE_OWN_ROLE(BAD_REQUEST),
    ROLE_UNCHANGED(BAD_REQUEST),
    NO_PERMISSION(FORBIDDEN),
    INFO_HIDDEN(FORBIDDEN),

    INSUFFICIENT_BALANCE(BAD_REQUEST),
    INVALID_AMOUNT(BAD_REQUEST),
    INSUFFICIENT_WITHDRAWAL(BAD_REQUEST),
    MASTER_WALLET_DRAINED(SERVICE_UNAVAILABLE),
    WITHDRAWAL_UNAVAILABLE(SERVICE_UNAVAILABLE),
    WALLET_NOT_FOUND(NOT_FOUND),

    INVALID_GAME_TYPE(BAD_REQUEST),
    GAME_NOT_FOUND(NOT_FOUND),
    INVALID_BET(BAD_REQUEST),
    GAME_OPTION_UNAVAILABLE(BAD_REQUEST),
    INVALID_CASE(BAD_REQUEST),
    INVALID_SEED(BAD_REQUEST),

    CANT_SELF_SEND(BAD_REQUEST),
    PRESENT_NOT_FOUND(NOT_FOUND),
    PRESENT_ALREADY_CLAIMED(BAD_REQUEST),

    CANT_BLOCK_SELF(BAD_REQUEST),
    ALREADY_BLOCKED(CONFLICT),
    BLOCKED(FORBIDDEN),

    LOTTERY_NOT_FOUND(NOT_FOUND),
    LOTTERY_SALES_CLOSED(BAD_REQUEST),
    LOTTERY_REFUND_CLOSED(BAD_REQUEST),
    NOT_ENOUGH_TICKETS(BAD_REQUEST),

    EXPERIENCE_NOT_FOUND(NOT_FOUND),
    REF_STORAGE_NOT_FOUND(NOT_FOUND),

    ALREADY_VERIFIED(BAD_REQUEST),

    BANNED(FORBIDDEN),
    INSUFFICIENT_EXPERIENCE(FORBIDDEN),
    MESSAGE_NOT_FOUND(NOT_FOUND),
    CANT_BAN_SELF(BAD_REQUEST),
    CANT_BAN_MODERATOR(FORBIDDEN),
    ALREADY_BANNED(BAD_REQUEST),
    NOT_BANNED(NOT_FOUND),
    CHAT_NOT_FOUND(NOT_FOUND),
    CANT_SELF_KICK(BAD_REQUEST),
    CANT_SELF_ADD(BAD_REQUEST),
    ALREADY_ADDED(CONFLICT),

    UNSUPPORTED_COIN(BAD_REQUEST),
    INVALID_ADDRESS(BAD_REQUEST),
    BAD_MNEMONIC(BAD_REQUEST),
    MASTER_WALLET_NOT_SET(BAD_REQUEST),
    CRYPTO_WALLET_NOT_FOUND(NOT_FOUND),
    UPSTREAM_ERROR(BAD_GATEWAY),

    SWEEP_SCHEDULE_NOT_FOUND(NOT_FOUND),

    FILE_NOT_FOUND(NOT_FOUND),
    FILENAME_TOO_LONG(BAD_REQUEST),
    DISK_QUOTA_EXCEEDED(CONFLICT),
    DISK_USAGE_NOT_FOUND(NOT_FOUND),

    INVALID_CURSOR(BAD_REQUEST),
    RATE_LIMITED(TOO_MANY_REQUESTS),

    VALIDATION_ERROR(BAD_REQUEST),
    MALFORMED_REQUEST(BAD_REQUEST),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    LENGTH_REQUIRED(HttpStatus.LENGTH_REQUIRED),
    ENDPOINT_NOT_FOUND(NOT_FOUND),
    INTERNAL_ERROR(INTERNAL_SERVER_ERROR);

    final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }
}
